### ISSUE TITLE
should phovea_clue be part of phovea_bundle_lib?

### ISSUE THREAD

**Issue by ngehlenborg** [phovea/phovea_clue#96]
Related to #95, What are the arguments for and against making `phovea_clue` part of the `phovea_bundle_library`?  

Or is it possible to build a separate bundle just for CLUE? 

Or how could it easily be added to projects that are built using `phovea_bundle_library`?

**Comment by thinkh** [comment]
With the current state of CLUE it doesn't make sense to include it in the phovea library, because:

1. It has dependencies to other libraries (bootstrap, jQuery, ...)
2. It uses own template and CSS files that need to be bundle with the library (question: how?)
3. It injects the CLUE templates (provenance graph, authoring, etc) in the current page, which is customized to Caleydo/Phovea pages and would break a different page application.

For this reason we decided (for now) to extract only the provenance storage to phovea_core so that we are able to clueify our standard visualizations (heatmap, scatterplot, etc) and store the provenance information in memory or localstorage. What the application does with this graph is up the developer/user.

As for the CLUE interface (provenance graph, authoring, etc) we need to think of a more general approach how encapsulate the templates. Instead of injecting the whole templates somewhere, the better solution might be to create different components (provenance graph, authoring, etc) that the developer can place into his application, at the position he wants.

**Comment by thinkh** [comment]
According to @sgratzl the second argument is not valid anymore, since Phovea uses webpack and can bundle everything independent of the file type.

An additional argument is that CLUE also provides the URL handling, which might conflict with the URL handling of the host application.

**Comment by sgratzl** [comment]
see also https://github.com/Caleydo/caleydo.github.io/issues/111
